### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by brandonhaslegs**
website

to do:
- [x] position card labels under their boxes. make text black
- [x] add enough padding at the bottom of the page so the button doesn't overlap the last image when you reach the bottom
- [x] make the gradient span the full height of the page, not repeat based on the height of the viewport
- [x] re-write the subheadline
- [x] Change "Code collab" to "Code collaboration"
- [x] try black seedling logo with black circle outline

Images:
- [x] org
- [x] pull push
- [x] github/gitlab mirroring
- [x] profile 
- [x] issues 
- [x] patches
- [ ] grant rfp proposals
- [ ] funded contributor
- [x] funded issues
- [x] p2p / protocol diagram (?)

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
There are just four screenshots left to make it finished. Not sure what they should be… 🤔 

@nassarhayat Do you think we could add some gifs or are you trying to keep this a bit more chill? I could imaging some cheesy sticker-type gifs dividing the sections. Something like these (we had these in an old version of radicle.xyz but didn't end up using them):

rose

local-first-4

key guy

**Comment by nassarhayat** [comment]
@brandonhaslegs - it's looking 👌🏽

- [x] you can find the images for the support and funding stuff in here: https://www.figma.com/file/FdyJx2YkV4LW6c0GvUjGhW/Radicle-DAO-focus?node-id=119%3A17609
- [ ] may need to create a commitment card on proposal around a funded contributor that shows streamed funds
- [x] need to add sub text to each card? a little more info on each feature would be helpful 
- [x] are you ok creating the architecture diagram? 
- [x] can we replace the hero image for the more recent one I created? https://www.figma.com/file/FdyJx2YkV4LW6c0GvUjGhW/Radicle-DAO-focus?node-id=233%3A28605
- [x] I would avoid GIFs for now as there is a fair bit for them to process already.

**Comment by brandonhaslegs** [comment]
Hey I filled in the rest but not sure what to do about the last two spots. Should this be something from the Drips work?

image

**Comment by nassarhayat** [comment]
> Hey I filled in the rest but not sure what to do about the last two spots. Should this be something from the Drips work?
> 
> image

Are you not comfortable adapting/using my example UI? Think it is enough to demonstrate the idea and vague enough in these shots that it can be adjusted as we build?

**Comment by brandonhaslegs** [comment]
No no, Sorry must have misunderstood you. can you share the screenshots you mean here? I'll put them in there.

**Comment by nassarhayat** [comment]
Ah. I shared this file with key screens I hacked together as demo. https://www.figma.com/file/FdyJx2YkV4LW6c0GvUjGhW/Radicle-DAO-focus?node-id=119%3A17609

**Comment by brandonhaslegs** [comment]
@nassarhayat should be good to go now. If it still doesn't look right, feel free to just replace any screenshots with ones you think are better suited.

**Pull request merged**
